### ISSUE TITLE
Update unmodeled pixels in ALFRESCO layers to have nodata value

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/rasdaman-ingest#17]
Some pixels were "not modeled" but were not included in the nodata mask for the postprocessing. E.g. the pixel intersecting Fairbanks. Re-process these data so that any un-modeled pixel contains a nodata value, and ingest.

**Comment by charparr** [comment]
Closed by #18 but the automatic closing of this issue didn't happen so closing now!
