### ISSUE TITLE
Add note to readme about wcst_import.sh script location

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/rasdaman-ingest#43]
Just a reminder to update the readme to have some note about the location of the `wcst_import.sh` script used to run all of our imports so far. There may be some inconsistency in how this script (and other utilities) make it into $PATH for direct accessibility. This will be important to consider if we ever consider automating download / import of coverages in batch. 

The script is at `/opt/rasdaman/bin` for directly calling that path, and including `source /etc/profile.d/rasdaman.sh` in your `~/.bashrc` will ensure it is available for simply calling `wcst_import.sh`.

**Comment by kyleredilla** [comment]
Simply running `source /etc/profile.d/rasdaman.sh` once may somehow add it to $PATH permanently. Also this info is presented when you login to either Zeus or Apollo, I just missed it.

**Comment by charparr** [comment]
@Kyle I think this well documented after your most recent readme update. Close it if you like?
