### ISSUE TITLE
Re-process + Re-ingest Degree Day Coverages to Truncate Historical Era-Interim to 1980-2010

### ISSUE THREAD

**Issue by charparr** [ua-snap/rasdaman-ingest#51]
Here’s why:

- 1979 ERA-Interim data only has 364 days, reflecting that quirky Jan. 2 start date.
- The 2015 ERA-Interim data only has 302 days reflecting that October-ish end date.
- Variable numbers of days is going to bias our computations of any degree day indicator, wet days, per year, etc.!
- So we basically HAVE to dump 1979 and 2015. We could run a 1980-2014 historical period but that’d be a bit of an odd duck in my opinion, and we’d be better off serving the the 30-year 1980-2010 climatology.

- [x] Re-process these notebooks, with the historical ERA-Interim truncated to 1980-2010
  - [x] [Design Index](https://github.com/ua-snap/rasdaman-ingest/blob/main/arctic_eds/design_indices/design_index_preprocessing.ipynb)
  - [x] [Degree Days](https://github.com/ua-snap/rasdaman-ingest/blob/main/arctic_eds/degree_days/dd_preprocessing.ipynb) 
- [x] Re-ingest these coverages on Apollo
  - [x] `degree_days_below_zero`
  - [x] `design_freezing_index`
  - [x] `design_thawing_index`
  - [x] `freezing_index`
  - [x] `heating_degree_days`
  - [x] `thawing_index`
- [ ] Re-ingest these coverages on Zeus
  - [ ] `degree_days_below_zero`
  - [x] `design_freezing_index`
  - [x] `design_thawing_index`
  - [ ] `freezing_index`
  - [ ] `heating_degree_days`
  - [ ] `thawing_index`

**Comment by charparr** [comment]
Actually, 1980-2009 is probably a better choice. Discuss before taking action on this ticket.

**Comment by kyleredilla** [comment]
@charparr it looks like the design indices were already created matching the new ERA-Interim period of 1980-2009 - can you sanity check me on that?

**Comment by charparr** [comment]
@kyleredilla yeah that is correct! I was just confused when making this issue, or made the issue before doing the fix and then ignored it :)

The 1980-2009 window is hardcoded in the design index prep notebook here: https://github.com/ua-snap/rasdaman-ingest/blob/main/arctic_eds/design_indices/design_index_preprocessing.ipynb

**Comment by kyleredilla** [comment]
Cool! I'll mark those complete then and open a PR for the DD preprocessing changes.

**Comment by charparr** [comment]
We're turning design indices into a module vs. a pre-baked endpoint, so I've stricken the migration of the `design` coverages to Zeus.

**Comment by charparr** [comment]
For the most recent October 2023 launch window we declined to mirror Apollo overages to Zeus (instead electing to just launch Apollo as the new prod instance) so this ticket can be closed because all that remained was to re-ingest the data to Zeus.
