### ISSUE TITLE
Update color maps in ingest scripts for coverages used in Arctic EDS

### ISSUE THREAD

**Issue by cstephen** [ua-snap/rasdaman-ingest#67]
Most Arctic EDS color maps were updated to use "intervals" instead of "ramp" to disable color interpolation. The color thresholds were changed too. See https://github.com/ua-snap/arctic-eds/pull/325 for details. We need to update the Rasdaman ingest scripts with these new color maps.

**Comment by charparr** [comment]
Closed by #77
